% Constant curvature for one segment. beta is the segment angle and l is
% the segment length.

function T = CCSegment(beta, l)

if beta == 0  % singularity
    T = [1, 0, 0, 0; ...
         0, 1, 0, 0; ...
         0, 0, 1, l; ...
         0, 0, 0, 1];
else
    T = [  cos(beta)   0,   -sin(beta)    l * ((1 - cos(beta))/beta); ...
           0,          1,    0,           0                         ; ...
           sin(beta),  0,    cos(beta),   l * (sin(beta)/beta)      ; ...
           0,          0,    0,           1                         ];
end
end