function T = CCSegment(segment_angle, segment_length)

T = [  cos(segment_angle),  sin(segment_angle),   0,   segment_length * ((1 - cos(segment_angle))/segment_angle); ...
      -sin(segment_angle),  cos(segment_angle),   0,   segment_length * (sin(segment_angle)/segment_angle)      ; ...
       0,                   0,                    1,   0                                ; ...
       0,                   0,                    0,   1                                ];

end