% Constant curvature for one segment. beta is the segment angle and l is
% the segment length.

function T = CCSegment(beta, l)

if beta == 0  % singularity
    T = [1, 0, 0, 0; ...
         0, 1, 0, l; ...
         0, 0, 1, 0; ...
         0, 0, 0, 1];
else
    T = [  cos(beta),  sin(beta),   0,   l * ((1 - cos(beta))/beta); ...
          -sin(beta),  cos(beta),   0,   l * (sin(beta)/beta)      ; ...
           0,          0,           1,   0                         ; ...
           0,          0,           0,   1                         ];
end

% % Taylor's series expansions O(x^10) for sin and cos to remove singularities
% px = l*((beta/2)+(beta^3/24)-(beta^5/720)+(beta^7/40320)-(beta^9/3628800));
% py = l*(1-(beta^2/6)+(beta^4/120)-(beta^6/5040)+(beta^8/362880));
% 
% T = [  cos(beta),  sin(beta),   0,    px; ...
%       -sin(beta),  cos(beta),   0,    py; ...
%        0,          0,           1,    0; ...
%        0,          0,           0,    1];
    
end